### ISSUE TITLE
Request from polkit does not work

### ISSUE THREAD

**Issue by martin3000** [philippmeisberger/pam-face#8] opened 2018-02-17 10:33 UTC
If you use the command
`systemctl start xxx` (without sudo), the command tries to get the authorization from pam-face. But this does not work. The error is:
` Unregistered Authentication Agent for unix-process:6810:35778 (system bus name :1.161, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)`

To avoid this, make the following change to pam-face.py in line 93:
`

    try:

        # check service type

        if pamh.service == "polkit-1":     # you get this if you make "systemctl start xxxx"

            raise Exception('Service polkit-1 ignored.')
`

**Comment by philippmeisberger** [comment] 2018-02-17 10:39
Cannot be reproduced on my Debian 9 with XFCE. Please try `synaptic` or `gparted`.

**Comment by martin3000** [comment] 2018-02-17 10:49
gparted and synaptic do not request root privileges like systemctl does.

**Comment by philippmeisberger** [comment] 2018-02-17 11:03
Please take a look into `/var/log/auth.log`. My contains following after using `systemctl restart bluetooth.service`:

`Feb 17 12:01:11 amon polkitd(authority=local): Registered Authentication Agent for unix-process:15048:327567 (system bus name :1.119 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale de_DE.UTF-8)
Feb 17 12:01:11 amon polkit-agent-helper-1: PAM Face: The user "root" is asking for permission for service "polkit-1".
Feb 17 12:01:11 amon polkit-agent-helper-1: PAM Face: The user was not added!`

**Comment by martin3000** [comment] 2018-02-17 13:27
On your side it is `PAM Face: The user "root" is asking ...`
Why is it user root if you did not use sudo?

I have `PAM Face: The user "bob" is asking... `

**Comment by philippmeisberger** [comment] 2018-02-20 16:25
Just calling `systemctl restart bluetooth.service` as non-root user brings up authentication dialog. Maybe `systemctl` calls `pkexec` if called as non-root user.

**Comment by martin3000** [comment] 2018-02-20 20:47
Without invoking pamface?

**Comment by philippmeisberger** [comment] 2018-02-20 20:50
What do you mean? `pkexec` invokes the current selected PAM module.

**Comment by philippmeisberger** [comment] 2020-04-25 08:48
I close this issue as the problem seems to be fixed. Feel free to reopen it.

**Closed as completed by philippmeisberger** 2020-04-25 08:48 UTC
